/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Modelo.Producto;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author cesaralx
 */
public class dialogDetalleProd extends javax.swing.JDialog {

    /**
     * Creates new form dialogDetalleProd
     * @param parent
     * @param ID
     * @param modal
     */
    
    Producto prod = new Producto();
    int id;
    
    public dialogDetalleProd(java.awt.Frame parent, boolean modal, int ID) throws IOException {
        super(parent, modal);
        id= ID;
        initComponents();
        llenarInfo();
    }
    

    private void llenarInfo() throws IOException{
        prod.consultaProductoID(id);
                
        String Finalpath = new File(prod.getImagen()).getAbsolutePath();
        Image image = ImageIO.read(new File(Finalpath));
        Image imageNew = image.getScaledInstance(198, 243, java.awt.Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(imageNew);
        jlbImagen.setIcon(icon);
        

        prod.getCategoria();
        jtxDescripcion.setText(prod.getDescripcionProd());
        jtxID.setText(String.valueOf(prod.getIdProducto()));
//        jtxDescripcion.setText(prod.getImagen());
        jtxNombreProducto.setText(prod.getNombreProducto());
        prod.getPedimento();
        jtxPrecioCom.setText(String.valueOf(prod.getPrecioCompra()));
        jtcPrecioVent.setText(String.valueOf(prod.getPrecioVenta()));
        jtxStock.setText(String.valueOf(prod.getStok()));
        jtxUbicacion.setText(prod.getUbicacion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbIdProducto = new javax.swing.JLabel();
        jtxID = new javax.swing.JTextField();
        jlbNombreProveedor1 = new javax.swing.JLabel();
        jtxNombreProducto = new javax.swing.JTextField();
        jlbDomicilioProveedor1 = new javax.swing.JLabel();
        jtxStock = new javax.swing.JTextField();
        jlbRfcProveedor2 = new javax.swing.JLabel();
        jtxPrecioCom = new javax.swing.JTextField();
        jlbRfcProveedor4 = new javax.swing.JLabel();
        jtcPrecioVent = new javax.swing.JTextField();
        jlbTelefonoProveedor1 = new javax.swing.JLabel();
        jtxDescripcion = new javax.swing.JTextField();
        jlbEmailProveedor1 = new javax.swing.JLabel();
        jtxUbicacion = new javax.swing.JTextField();
        jlbImagen = new javax.swing.JLabel();
        jbnActualizarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jlbIdProducto.setDisplayedMnemonic('b');
        jlbIdProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbIdProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIdProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ID Card_25px_2.png"))); // NOI18N
        jlbIdProducto.setText("ID producto:");
        jlbIdProducto.setToolTipText("");
        jlbIdProducto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbIdProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxID.setBorder(null);
        jtxID.setEnabled(false);

        jlbNombreProveedor1.setDisplayedMnemonic('b');
        jlbNombreProveedor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNombreProveedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNombreProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Business Building_25px_5.png"))); // NOI18N
        jlbNombreProveedor1.setText("Nombre:");
        jlbNombreProveedor1.setToolTipText("");
        jlbNombreProveedor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbNombreProveedor1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxNombreProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxNombreProducto.setForeground(new java.awt.Color(102, 102, 102));
        jtxNombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxNombreProducto.setBorder(null);

        jlbDomicilioProveedor1.setDisplayedMnemonic('d');
        jlbDomicilioProveedor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbDomicilioProveedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDomicilioProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Home_25px_3.png"))); // NOI18N
        jlbDomicilioProveedor1.setText("Stock:");
        jlbDomicilioProveedor1.setToolTipText("");
        jlbDomicilioProveedor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbDomicilioProveedor1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxStock.setBorder(null);

        jlbRfcProveedor2.setDisplayedMnemonic('b');
        jlbRfcProveedor2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbRfcProveedor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRfcProveedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Postcard With Barcode_25px_1.png"))); // NOI18N
        jlbRfcProveedor2.setText("Precio Compra:");
        jlbRfcProveedor2.setToolTipText("");
        jlbRfcProveedor2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbRfcProveedor2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxPrecioCom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxPrecioCom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxPrecioCom.setBorder(null);

        jlbRfcProveedor4.setDisplayedMnemonic('b');
        jlbRfcProveedor4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbRfcProveedor4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRfcProveedor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Postcard With Barcode_25px_1.png"))); // NOI18N
        jlbRfcProveedor4.setText("Precio Venta:");
        jlbRfcProveedor4.setToolTipText("");
        jlbRfcProveedor4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbRfcProveedor4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtcPrecioVent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtcPrecioVent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtcPrecioVent.setBorder(null);

        jlbTelefonoProveedor1.setDisplayedMnemonic('b');
        jlbTelefonoProveedor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbTelefonoProveedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTelefonoProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Phone_25px.png"))); // NOI18N
        jlbTelefonoProveedor1.setText("Descripcion:");
        jlbTelefonoProveedor1.setToolTipText("");
        jlbTelefonoProveedor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbTelefonoProveedor1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxDescripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxDescripcion.setBorder(null);

        jlbEmailProveedor1.setDisplayedMnemonic('b');
        jlbEmailProveedor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbEmailProveedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbEmailProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Mail_25px.png"))); // NOI18N
        jlbEmailProveedor1.setText("Ubicacion:");
        jlbEmailProveedor1.setToolTipText("");
        jlbEmailProveedor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbEmailProveedor1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxUbicacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxUbicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxUbicacion.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbEmailProveedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbTelefonoProveedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtxDescripcion))
                        .addGap(132, 132, 132))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbRfcProveedor4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jlbDomicilioProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbNombreProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxStock, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)
                                .addComponent(jtxPrecioCom, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtcPrecioVent, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)))
                .addComponent(jlbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(166, 166, 166)
                            .addComponent(jtxID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(273, 273, 273)
                            .addComponent(jlbRfcProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(403, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbIdProducto)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbNombreProveedor1)
                            .addComponent(jtxNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbDomicilioProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxPrecioCom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbRfcProveedor4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtcPrecioVent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTelefonoProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEmailProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jtxID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                    .addComponent(jlbRfcProveedor2)
                    .addContainerGap(215, Short.MAX_VALUE)))
        );

        jbnActualizarProducto.setBackground(new java.awt.Color(145, 36, 36));
        jbnActualizarProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbnActualizarProducto.setForeground(new java.awt.Color(255, 255, 255));
        jbnActualizarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Sync_48px_1.png"))); // NOI18N
        jbnActualizarProducto.setText("Actualizar producto");
        jbnActualizarProducto.setBorderPainted(false);
        jbnActualizarProducto.setContentAreaFilled(false);
        jbnActualizarProducto.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Sync_48px_2.png"))); // NOI18N
        jbnActualizarProducto.setSelected(true);
        jbnActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnActualizarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnActualizarProducto)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbnActualizarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbnActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnActualizarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnActualizarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogDetalleProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogDetalleProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogDetalleProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogDetalleProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                dialogDetalleProd dialog = new dialogDetalleProd(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbnActualizarProducto;
    private javax.swing.JLabel jlbDomicilioProveedor1;
    private javax.swing.JLabel jlbEmailProveedor1;
    private javax.swing.JLabel jlbIdProducto;
    private javax.swing.JLabel jlbImagen;
    private javax.swing.JLabel jlbNombreProveedor1;
    private javax.swing.JLabel jlbRfcProveedor2;
    private javax.swing.JLabel jlbRfcProveedor4;
    private javax.swing.JLabel jlbTelefonoProveedor1;
    private javax.swing.JTextField jtcPrecioVent;
    private javax.swing.JTextField jtxDescripcion;
    private javax.swing.JTextField jtxID;
    private javax.swing.JTextField jtxNombreProducto;
    private javax.swing.JTextField jtxPrecioCom;
    private javax.swing.JTextField jtxStock;
    private javax.swing.JTextField jtxUbicacion;
    // End of variables declaration//GEN-END:variables
}
