/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;


import java.io.File;
import javax.swing.JFileChooser;


/**
 *
 * @author alexi
 */
public class dialogProductos extends javax.swing.JDialog {

    /**
     * Creates new form dialogProductos
     * @param parent
     * @param modal
     */
    public dialogProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
        public void seleccionarImagen(dialogProductos frame) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(frame);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Archivo seleccionado: " + selectedFile.getAbsolutePath()); //lofgile
//            frmm.jtfImagen.setText(selectedFile.getAbsolutePath());
            jtxImagen.setText(selectedFile.getAbsolutePath());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbIdProveedor1 = new javax.swing.JLabel();
        jtxProveedor1 = new javax.swing.JTextField();
        jtxNombreProveedor1 = new javax.swing.JTextField();
        jlbNombreProveedor1 = new javax.swing.JLabel();
        jlbDomicilioProveedor1 = new javax.swing.JLabel();
        jlbTelefonoProveedor1 = new javax.swing.JLabel();
        jlbEmailProveedor1 = new javax.swing.JLabel();
        jtxEmailProveedor1 = new javax.swing.JTextField();
        jtxTelefonoProveedor1 = new javax.swing.JTextField();
        jtxDomicilioProveedor1 = new javax.swing.JTextField();
        jlbRfcProveedor2 = new javax.swing.JLabel();
        jlbRfcProveedor1 = new javax.swing.JLabel();
        jtxRfcProveedor1 = new javax.swing.JTextField();
        jbnExaminar = new javax.swing.JButton();
        jtxImagen = new javax.swing.JTextField();
        jbnAgregarProveedorNuevo = new javax.swing.JButton();
        jbnCancelarProveedorNuevo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Producto"));

        jlbIdProveedor1.setDisplayedMnemonic('b');
        jlbIdProveedor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbIdProveedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIdProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ID Card_25px_2.png"))); // NOI18N
        jlbIdProveedor1.setText("ID proveedor:");
        jlbIdProveedor1.setToolTipText("");
        jlbIdProveedor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbIdProveedor1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxProveedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxProveedor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxProveedor1.setBorder(null);
        jtxProveedor1.setEnabled(false);

        jtxNombreProveedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxNombreProveedor1.setForeground(new java.awt.Color(102, 102, 102));
        jtxNombreProveedor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxNombreProveedor1.setBorder(null);

        jlbNombreProveedor1.setDisplayedMnemonic('b');
        jlbNombreProveedor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNombreProveedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNombreProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Business Building_25px_5.png"))); // NOI18N
        jlbNombreProveedor1.setText("Nombre:");
        jlbNombreProveedor1.setToolTipText("");
        jlbNombreProveedor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbNombreProveedor1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jlbDomicilioProveedor1.setDisplayedMnemonic('d');
        jlbDomicilioProveedor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbDomicilioProveedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDomicilioProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Home_25px_3.png"))); // NOI18N
        jlbDomicilioProveedor1.setText("Domicilio:");
        jlbDomicilioProveedor1.setToolTipText("");
        jlbDomicilioProveedor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbDomicilioProveedor1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jlbTelefonoProveedor1.setDisplayedMnemonic('b');
        jlbTelefonoProveedor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbTelefonoProveedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTelefonoProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Phone_25px.png"))); // NOI18N
        jlbTelefonoProveedor1.setText("Telefono:");
        jlbTelefonoProveedor1.setToolTipText("");
        jlbTelefonoProveedor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbTelefonoProveedor1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jlbEmailProveedor1.setDisplayedMnemonic('b');
        jlbEmailProveedor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbEmailProveedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbEmailProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Mail_25px.png"))); // NOI18N
        jlbEmailProveedor1.setText("Email:");
        jlbEmailProveedor1.setToolTipText("");
        jlbEmailProveedor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbEmailProveedor1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxEmailProveedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxEmailProveedor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxEmailProveedor1.setBorder(null);

        jtxTelefonoProveedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxTelefonoProveedor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxTelefonoProveedor1.setBorder(null);

        jtxDomicilioProveedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxDomicilioProveedor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxDomicilioProveedor1.setBorder(null);

        jlbRfcProveedor2.setDisplayedMnemonic('b');
        jlbRfcProveedor2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbRfcProveedor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRfcProveedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Postcard With Barcode_25px_1.png"))); // NOI18N
        jlbRfcProveedor2.setText("RFC:");
        jlbRfcProveedor2.setToolTipText("");
        jlbRfcProveedor2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbRfcProveedor2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jlbRfcProveedor1.setDisplayedMnemonic('b');
        jlbRfcProveedor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbRfcProveedor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRfcProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Postcard With Barcode_25px_1.png"))); // NOI18N
        jlbRfcProveedor1.setText("Imagen:");
        jlbRfcProveedor1.setToolTipText("");
        jlbRfcProveedor1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbRfcProveedor1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jtxRfcProveedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxRfcProveedor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxRfcProveedor1.setBorder(null);

        jbnExaminar.setText("Examinar");
        jbnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnExaminarActionPerformed(evt);
            }
        });

        jtxImagen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxImagen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxImagen.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTelefonoProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbDomicilioProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbEmailProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxEmailProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jlbRfcProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbnExaminar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxTelefonoProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jlbRfcProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jtxRfcProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtxDomicilioProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jlbIdProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jlbNombreProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxNombreProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbIdProveedor1)
                    .addComponent(jtxProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlbNombreProveedor1))
                    .addComponent(jtxNombreProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlbDomicilioProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxDomicilioProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxTelefonoProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxRfcProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTelefonoProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbRfcProveedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxEmailProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbnExaminar)
                                .addComponent(jtxImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jlbEmailProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbRfcProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jbnAgregarProveedorNuevo.setBackground(new java.awt.Color(145, 36, 36));
        jbnAgregarProveedorNuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbnAgregarProveedorNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jbnAgregarProveedorNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Plus_48px.png"))); // NOI18N
        jbnAgregarProveedorNuevo.setText("Agregar producto");
        jbnAgregarProveedorNuevo.setBorderPainted(false);
        jbnAgregarProveedorNuevo.setContentAreaFilled(false);
        jbnAgregarProveedorNuevo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Plus_48px_1.png"))); // NOI18N
        jbnAgregarProveedorNuevo.setSelected(true);
        jbnAgregarProveedorNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAgregarProveedorNuevoActionPerformed(evt);
            }
        });

        jbnCancelarProveedorNuevo1.setBackground(new java.awt.Color(145, 36, 36));
        jbnCancelarProveedorNuevo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbnCancelarProveedorNuevo1.setForeground(new java.awt.Color(255, 255, 255));
        jbnCancelarProveedorNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Plus_48px.png"))); // NOI18N
        jbnCancelarProveedorNuevo1.setText("Cancelar");
        jbnCancelarProveedorNuevo1.setBorderPainted(false);
        jbnCancelarProveedorNuevo1.setContentAreaFilled(false);
        jbnCancelarProveedorNuevo1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Plus_48px_1.png"))); // NOI18N
        jbnCancelarProveedorNuevo1.setSelected(true);
        jbnCancelarProveedorNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCancelarProveedorNuevo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jbnAgregarProveedorNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnCancelarProveedorNuevo1)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnAgregarProveedorNuevo)
                    .addComponent(jbnCancelarProveedorNuevo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnExaminarActionPerformed
               seleccionarImagen(this);

    }//GEN-LAST:event_jbnExaminarActionPerformed

    private void jbnAgregarProveedorNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAgregarProveedorNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnAgregarProveedorNuevoActionPerformed

    private void jbnCancelarProveedorNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCancelarProveedorNuevo1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbnCancelarProveedorNuevo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                dialogProductos dialog = new dialogProductos(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbnAgregarProveedorNuevo;
    private javax.swing.JButton jbnCancelarProveedorNuevo1;
    private javax.swing.JButton jbnExaminar;
    private javax.swing.JLabel jlbDomicilioProveedor1;
    private javax.swing.JLabel jlbEmailProveedor1;
    private javax.swing.JLabel jlbIdProveedor1;
    private javax.swing.JLabel jlbNombreProveedor1;
    private javax.swing.JLabel jlbRfcProveedor1;
    private javax.swing.JLabel jlbRfcProveedor2;
    private javax.swing.JLabel jlbTelefonoProveedor1;
    private javax.swing.JTextField jtxDomicilioProveedor1;
    private javax.swing.JTextField jtxEmailProveedor1;
    public javax.swing.JTextField jtxImagen;
    private javax.swing.JTextField jtxNombreProveedor1;
    private javax.swing.JTextField jtxProveedor1;
    private javax.swing.JTextField jtxRfcProveedor1;
    private javax.swing.JTextField jtxTelefonoProveedor1;
    // End of variables declaration//GEN-END:variables
}
