package Ventanas;

import javax.swing.JFrame;

public class frmMenu2 extends javax.swing.JFrame {

    frmLogin inicio;
    
    public frmMenu2(frmLogin l) {
        inicio= l;
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbnCerrar = new javax.swing.JButton();
        jlbLogo = new javax.swing.JLabel();
        jbnProducto = new javax.swing.JButton();
        jbnPedidos = new javax.swing.JButton();
        jbnDescuento = new javax.swing.JButton();
        jbnEmpleado = new javax.swing.JButton();
        jbnProveedor = new javax.swing.JButton();
        jbnVenta = new javax.swing.JButton();
        jbnClientes = new javax.swing.JButton();
        jbnCompra = new javax.swing.JButton();
        jbnRerportes = new javax.swing.JButton();
        jbnEmpresas = new javax.swing.JButton();
        jpInferior = new javax.swing.JPanel();
        jpCliente = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(100);
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(1154, 644));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1160, 654));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.CardLayout());

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jbnCerrar.setBackground(new java.awt.Color(145, 36, 36));
        jbnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Close Window_50px_1.png"))); // NOI18N
        jbnCerrar.setBorderPainted(false);
        jbnCerrar.setContentAreaFilled(false);
        jbnCerrar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Close Window_60px.png"))); // NOI18N
        jbnCerrar.setSelected(true);
        jbnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jbnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jlbLogo.setBackground(new java.awt.Color(153, 0, 0));
        jlbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoTriton.png"))); // NOI18N

        jbnProducto.setBackground(new java.awt.Color(0, 51, 204));
        jbnProducto.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/producto_128.png"))); // NOI18N
        jbnProducto.setText("Producto");
        jbnProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbnProducto.setBorderPainted(false);
        jbnProducto.setContentAreaFilled(false);
        jbnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnProducto.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/producto_150.png"))); // NOI18N
        jbnProducto.setSelected(true);
        jbnProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnProductoActionPerformed(evt);
            }
        });

        jbnPedidos.setBackground(new java.awt.Color(0, 51, 204));
        jbnPedidos.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pedido_128.png"))); // NOI18N
        jbnPedidos.setText("Pedidos");
        jbnPedidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbnPedidos.setBorderPainted(false);
        jbnPedidos.setContentAreaFilled(false);
        jbnPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnPedidos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pedido_150.png"))); // NOI18N
        jbnPedidos.setSelected(true);
        jbnPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnPedidosActionPerformed(evt);
            }
        });

        jbnDescuento.setBackground(new java.awt.Color(0, 51, 204));
        jbnDescuento.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbnDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/descuento_128.png"))); // NOI18N
        jbnDescuento.setText("Descuento");
        jbnDescuento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbnDescuento.setBorderPainted(false);
        jbnDescuento.setContentAreaFilled(false);
        jbnDescuento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnDescuento.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/descuento_150.png"))); // NOI18N
        jbnDescuento.setSelected(true);
        jbnDescuento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnDescuentoActionPerformed(evt);
            }
        });

        jbnEmpleado.setBackground(new java.awt.Color(145, 36, 36));
        jbnEmpleado.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbnEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empleado_128.png"))); // NOI18N
        jbnEmpleado.setText("Empleado");
        jbnEmpleado.setBorderPainted(false);
        jbnEmpleado.setContentAreaFilled(false);
        jbnEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnEmpleado.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empleado_150.png"))); // NOI18N
        jbnEmpleado.setSelected(true);
        jbnEmpleado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnEmpleadoActionPerformed(evt);
            }
        });

        jbnProveedor.setBackground(new java.awt.Color(145, 36, 36));
        jbnProveedor.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/proveedor_128.png"))); // NOI18N
        jbnProveedor.setText("Proveedor");
        jbnProveedor.setBorderPainted(false);
        jbnProveedor.setContentAreaFilled(false);
        jbnProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnProveedor.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/proveedor_150.png"))); // NOI18N
        jbnProveedor.setSelected(true);
        jbnProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnProveedorActionPerformed(evt);
            }
        });

        jbnVenta.setBackground(new java.awt.Color(0, 51, 204));
        jbnVenta.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/venta_128.png"))); // NOI18N
        jbnVenta.setText("Venta ");
        jbnVenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbnVenta.setBorderPainted(false);
        jbnVenta.setContentAreaFilled(false);
        jbnVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnVenta.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/venta_150.png"))); // NOI18N
        jbnVenta.setSelected(true);
        jbnVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnVentaActionPerformed(evt);
            }
        });

        jbnClientes.setBackground(new java.awt.Color(0, 51, 204));
        jbnClientes.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cliente_128.png"))); // NOI18N
        jbnClientes.setText("Clientes");
        jbnClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbnClientes.setBorderPainted(false);
        jbnClientes.setContentAreaFilled(false);
        jbnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnClientes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cliente_150.png"))); // NOI18N
        jbnClientes.setSelected(true);
        jbnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnClientesActionPerformed(evt);
            }
        });

        jbnCompra.setBackground(new java.awt.Color(0, 51, 204));
        jbnCompra.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/compra_128.png"))); // NOI18N
        jbnCompra.setText("Compra");
        jbnCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbnCompra.setBorderPainted(false);
        jbnCompra.setContentAreaFilled(false);
        jbnCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnCompra.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Compra_150.png"))); // NOI18N
        jbnCompra.setSelected(true);
        jbnCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCompraActionPerformed(evt);
            }
        });

        jbnRerportes.setBackground(new java.awt.Color(0, 51, 204));
        jbnRerportes.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbnRerportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/reporte_128.png"))); // NOI18N
        jbnRerportes.setText("Reportes");
        jbnRerportes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbnRerportes.setBorderPainted(false);
        jbnRerportes.setContentAreaFilled(false);
        jbnRerportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnRerportes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/reporte_150.png"))); // NOI18N
        jbnRerportes.setSelected(true);
        jbnRerportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnRerportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnRerportesActionPerformed(evt);
            }
        });

        jbnEmpresas.setBackground(new java.awt.Color(0, 51, 204));
        jbnEmpresas.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbnEmpresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empresa_128.png"))); // NOI18N
        jbnEmpresas.setText("Empresa");
        jbnEmpresas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbnEmpresas.setBorderPainted(false);
        jbnEmpresas.setContentAreaFilled(false);
        jbnEmpresas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnEmpresas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empresa_150.png"))); // NOI18N
        jbnEmpresas.setSelected(true);
        jbnEmpresas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnEmpresasActionPerformed(evt);
            }
        });

        jpInferior.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jpInferiorLayout = new javax.swing.GroupLayout(jpInferior);
        jpInferior.setLayout(jpInferiorLayout);
        jpInferiorLayout.setHorizontalGroup(
            jpInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpInferiorLayout.setVerticalGroup(
            jpInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbnDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jbnRerportes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jbnEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addComponent(jpInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMenuLayout.createSequentialGroup()
                                .addComponent(jbnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jbnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpMenuLayout.createSequentialGroup()
                                .addComponent(jbnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jbnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpMenuLayout.createSequentialGroup()
                                .addComponent(jbnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jbnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpMenuLayout.createSequentialGroup()
                                .addComponent(jbnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jbnDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbnRerportes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbnEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(jpMenu, "card2");

        jpCliente.setBackground(new java.awt.Color(255, 255, 255));
        jpCliente.setMinimumSize(new java.awt.Dimension(1150, 610));
        jpCliente.setName(""); // NOI18N
        jpCliente.setPreferredSize(new java.awt.Dimension(1154, 654));

        jPanel6.setBackground(new java.awt.Color(22, 114, 185));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cliente_128.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout jpClienteLayout = new javax.swing.GroupLayout(jpCliente);
        jpCliente.setLayout(jpClienteLayout);
        jpClienteLayout.setHorizontalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(883, 883, 883))
        );
        jpClienteLayout.setVerticalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.add(jpCliente, "card2");

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel1, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbnCerrarActionPerformed

    private void jbnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnProductoActionPerformed

    private void jbnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnPedidosActionPerformed

    private void jbnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnDescuentoActionPerformed

    private void jbnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnEmpleadoActionPerformed

    private void jbnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnProveedorActionPerformed

    private void jbnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnVentaActionPerformed

    private void jbnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnClientesActionPerformed
       jPanel7.removeAll();
       jPanel7.add(jpCliente);
       jpCliente.repaint();
       jpCliente.revalidate();
    }//GEN-LAST:event_jbnClientesActionPerformed

    private void jbnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnCompraActionPerformed

    private void jbnRerportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnRerportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnRerportesActionPerformed

    private void jbnEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnEmpresasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnEmpresasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jbnCerrar;
    private javax.swing.JButton jbnClientes;
    private javax.swing.JButton jbnCompra;
    private javax.swing.JButton jbnDescuento;
    private javax.swing.JButton jbnEmpleado;
    private javax.swing.JButton jbnEmpresas;
    private javax.swing.JButton jbnPedidos;
    private javax.swing.JButton jbnProducto;
    private javax.swing.JButton jbnProveedor;
    private javax.swing.JButton jbnRerportes;
    private javax.swing.JButton jbnVenta;
    private javax.swing.JLabel jlbLogo;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpInferior;
    private javax.swing.JPanel jpMenu;
    // End of variables declaration//GEN-END:variables
}
